import urllib.request
from bs4 import BeautifulSoup

response = urllib.request.urlopen('https://stackoverflow.com/questions/42611593/how-to-solve-syntaxerror-on-autogenerated-manage-py')
html = response.read()

soup = BeautifulSoup(html, 'html.parser')

question_title = soup.find("a",{"class":"question-hyperlink"}).text
question_body = soup.find("div",{"class":"question"}).find("p").text
question = [question_title,question_body]
# print(questios)

answers = soup.find_all("div",{"class":"answer"})

# print(len(answers))
answer_list = []
for ans in answers:
	answer_list.append(ans.find("p").text)

print(answer_list)