import urllib.request
import pprint
from bs4 import BeautifulSoup

data = {'question':'', 'answers':''}
question = {'desc':'', 'author':'', 'upvotes':''}
answers_list = []
answer = {'desc':'', 'author':'', 'upvotes':''}

url = 'https://stackoverflow.com/questions/42611593/how-to-solve-syntaxerror-on-autogenerated-manage-py'
response = urllib.request.urlopen(url)
html = response.read()

soup = BeautifulSoup(html, 'html.parser')

#extracting question
question_title = soup.find("a",{"class":"question-hyperlink"}).text
question_body = soup.find("div",{"class":"question"})
qbody = question_body.find_all("p")

qb_list = []
for p in qbody:
	qb_list.append(p.text)

q_desc = question_title
for q in qb_list:
	q_desc += "\n" + q

author = question_body.find_all("div",{"class":"user-details"})
auth_list = []
for auth in author:
	auth_list.append(auth.find("a"))
del auth_list[0]
q_author = auth_list.pop(0).text

q_upvotes = question_body.find("span").text

question['desc'] = q_desc
question['author'] = q_author
question['upvotes'] = q_upvotes

answer_blocks = soup.find_all("div",{"class":"answercell post-layout--right"})
for block in answer_blocks:
	ans_p = block.find_all("p")
	ans_desc = ''
	for desc in ans_p:
		ans_desc += " " + desc.text
	answer['desc'] = ans_desc
	author = block.find("div",{"class":"user-details"}).find("a").text
	answer['author'] = author
	ans_upvotes = block.find_previous_sibling("div",{"class":"votecell post-layout--left"}).find("div",{"class":"vote"}).find("span").text
	answer['upvotes'] = ans_upvotes
	
	# answers_list.append(answer)
	pprint.pprint(answers_list)

# pprint.pprint(answers_list)
