import urllib.request
from bs4 import BeautifulSoup

data = {'question':'', 'answers':[]}
question = {'desc':'', 'author':'', 'upvotes':''}
answers = {'desc':'', 'author':'', 'upvotes':''}

url = 'https://stackoverflow.com/questions/42611593/how-to-solve-syntaxerror-on-autogenerated-manage-py'
response = urllib.request.urlopen(url)
html = response.read()

soup = BeautifulSoup(html, 'html.parser')

#extracting question
question_title = soup.find("a",{"class":"question-hyperlink"}).text
question_body = soup.find("div",{"class":"question"})
qbody = question_body.find_all("p")

qb_list = []
for p in qbody:
	qb_list.append(p.text)

q_desc = question_title
for q in qb_list:
	q_desc += "\n" + q

author = question_body.find_all("div",{"class":"user-details"})
auth_list = []
for auth in author:
	auth_list.append(auth.find("a"))
del auth_list[0]
q_author = auth_list.pop(0).text
# print(q_author)

q_upvotes = question_body.find("span").text
print(q_upvotes)

question['desc'] = q_desc
question['author'] = q_author
# data['question'] = question

# print(data)

#extracting answer
answ = soup.find_all("div",{"class":"answer"})
answer_list = []
for ans in answ:
	answer_list.append(ans.find("p").text)


#still have to extract author name
#there is a None data type that mixes so it needs to be filtered